### ISSUE TITLE
User Resource defined in API is not overwriting the base User

### ISSUE THREAD

**Issue by spersico** [ebryn/jsonapi-ts#119]
If the api defines a user Resource with attributes **X** and **Y**, on a GET to user the response only has what's defined in the base user (right now, that's only the **username** and **password** attributes).

So basically we can't get the whole user on a request.

Example
![image](https://user-images.githubusercontent.com/10502605/57234601-64c8d780-6ff7-11e9-97e7-e631c6c4a5b6.png)

**Comment by joelalejandro** [comment]
This is expected behavior. As we discussed it in the call, any changes require to extend the UserProcessor and reassign the resource class.
