### ISSUE TITLE
Remove Default permissions of the base UserProcessor

### ISSUE THREAD

**Issue by spersico** [ebryn/jsonapi-ts#127]
https://github.com/ebryn/jsonapi-ts/blob/d8370659b73ee819e4405a69b2e0bf405964121a/src/processors/user-processor.ts#L40
This check makes it difficult to extend the base userProcessor, and establish custom permissions (like an admin role to list all users).
Like this:
![image](https://user-images.githubusercontent.com/10502605/57262640-602a1080-7043-11e9-9594-425db9c64f7b.png)
I can't user super.get(...) because that will pass through to the base userProcessor and block the request just the same.

This is blocking chameleon.

**Comment by joelalejandro** [comment]
Discussed, we agreed that while this leaves the User resource unprotected, maybe JSONAPI doesn't need to be opinionated about it. It should be the implementer's responsibility to protect the resource.
