### ISSUE TITLE
KnexProcessor is trying to fetch computed properties from database

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#156]
If I declare a computed property in the `attributes` hash of a custom processor that extends from KnexProcessor<T>, the SQL builder includes it in the query, making it fail.

**Comment by spersico** [comment]
![image](https://user-images.githubusercontent.com/10502605/58116712-596ad400-7bd3-11e9-9ae3-586f1fe8f1ab.png)
Can you provide more data/context? I'm not being able to replicate this

**Comment by spersico** [comment]
Closing, false alarm
