### ISSUE TITLE
Built-in roles and permissions

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#166]
@rtablada suggested a simpler way, exposing two callback methods that the auth service can invoke to fill in the data about roles and permissions.

Original proposal:

> In order to provide more granular control in terms of endpoint authorization, a logical next step would be to expand the current `UserManagementAddon` with two new resources:
> 
> - **Role:** represents a group of permissions. A User can have many roles.
> 
> - **Permissions:** represents a capability to perform a certain action. Can belong to multiple roles. A User can have multiple permissions.
> 
> We'd also add new helpers to match these resources to a User: `IfUserHasRole`, `IfUserHasEveryRole`, `IfUserDoesNotHaveRole`, `IfUserHasPermission`, `IfUserHasEveryPermission`, `IfUserDoesNotHavePermission`.
> 
> What should the developer do in order to take advantage of this new feature?
> 
> 1) Use the built-in new resources or extend and pass them to the options for the `UserManagementAddon`.
> 
> 2) Use the *Role and *Permission helpers along with `@Authorize`.
> 
> Both `Role` and `Permission` resources have a `name: string` attribute and a `granted: boolean` attribute. Like any other resource, they can be handled by custom processors to adapt to pre-existing databases or any custom logic the developer wants to implement.

**Comment by rtablada** [comment]
Hmm I’m wondering if we should instead codify `getRolesForUser` and `getPermissionsForUser` in the auth service so that it’s more customizable to fit existing schemas?

**Comment by joelalejandro** [comment]
@rtablada If you want to customize that, you can create a `RoleProcessor` and a `PermissionProcessor`, which follows the same pattern that the rest of the entities. It'd be a matter of overriding the `get` operation, I think.

**Comment by rtablada** [comment]
Yeah some system may even have roles/permissions as strings on a JSON blob on the user or DB settings or LDAP or other ways where it’s not a true relationship or resource.
